services:
  - type: web
    name: bmi-currency-app
    env: python
    buildCommand: ""
    startCommand: gunicorn bmi_project_main.wsgi:application # <-- ИСПРАВЛЕНО
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bmi_project_main.settings 