services:
  - type: web
    name: bmi-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bmi_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bmi_project.settings
