# Exported from Render on 2025-07-02T14:35:04Z
services:
- type: web
  name: CalculatorProject
  runtime: python
  repo: https://github.com/Rara098765/CalculatorProject
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  autoDeployTrigger: commit
version: "1"
